bank1=['tiger', 'grass', 'goat']
bank2=[]
bank1.remove('goat')
bank2.append('goat')
print("bank1 has the following in the next tripof the farmer", bank1)
print("bank2 has the following in the next tripof the farmer", bank2)
bank1.remove('grass')
bank2.append('grass')
print("bank1 has the following in the next tripof the farmer", bank1)
print("bank2 has the following in the next tripof the farmer", bank2)
bank2.remove('goat')
bank1.append('goat')
print("bank1 has the following in the next tripof the farmer", bank1)
print("bank2 has the following in the next tripof the farmer", bank2)
bank1.remove('tiger')
bank2.append('tiger')
print("bank1 has the following in the next tripof the farmer", bank1)
print("bank2 has the following in the next tripof the farmer", bank2)
bank1.remove('goat')
bank2.append('goat')
print(bank1)
print(bank2)
